// Public catalogue metadata stays independent of the lazy-loaded demonstrations.
const define = (id, name, category, folder, component, showcase, summary, demo, kind) => ({
  id: `builtin-${id}`,
  name,
  category,
  folder,
  component,
  showcase,
  summary,
  demo,
  kind,
  path: `src/components/${folder}/${component}.jsx`,
});

export const categories = [
  'Buttons',
  'Forms',
  'Navigation',
  'Cards',
  'Feedback',
  'Motion',
  'Display',
];
export const entries = [
  define(
    'relief-button',
    'Raised button',
    'Buttons',
    'Button',
    'Button',
    'ButtonShowcase',
    'A satisfying press. Six variants, three sizes, and clear action feedback.',
    'demos/example-default',
  ),
  define(
    'reaction-button',
    'Reaction Button',
    'Buttons',
    'ReactionButton',
    'ReactionButton',
    'ReactionButtonShowcase',
    'Likes, favorites and reactions with a little personality.',
    'ReactionButtonDemos',
  ),
  define(
    'input',
    'Input',
    'Forms',
    'Forms',
    'Input',
    'FormsShowcase',
    'A considered starting point for every form.',
    'FormDemos',
    'input',
  ),
  define(
    'field',
    'Field',
    'Forms',
    'Forms',
    'Input',
    'FormsShowcase',
    'Labels, help and validation that belong together.',
    'FormDemos',
    'field',
  ),
  define(
    'input-group',
    'Input Group',
    'Forms',
    'Forms',
    'InputGroup',
    'FormsShowcase',
    'Inputs, icons and actions on one continuous surface.',
    'EnrichedDemos',
    'input-group',
  ),
  define(
    'textarea',
    'Textarea',
    'Forms',
    'Forms',
    'Textarea',
    'FormsShowcase',
    'Room for longer thoughts, with resize and character counts.',
    'EnrichedDemos',
    'textarea',
  ),
  define(
    'number-field',
    'Number Field',
    'Forms',
    'Forms',
    'NumberField',
    'FormsShowcase',
    'Precise numbers with tactile step controls.',
    'NumericDemos',
    'number-field',
  ),
  define(
    'otp-field',
    'OTP Field',
    'Forms',
    'Forms',
    'OtpField',
    'FormsShowcase',
    'Verification codes with keyboard and paste support.',
    'NumericDemos',
    'otp-field',
  ),
  define(
    'checkbox',
    'Checkbox',
    'Forms',
    'Checkbox',
    'Checkbox',
    'CheckboxShowcase',
    'One choice or a whole group. Every state feels right.',
    'CheckboxDemos',
  ),
  define(
    'radio-group',
    'Radio Group',
    'Forms',
    'Selection',
    'Selection',
    'SelectionShowcase',
    'One considered choice, from a list to a grid of cards.',
    'SelectionDemos',
    'radio',
  ),
  define(
    'switch',
    'Switch',
    'Forms',
    'Selection',
    'Selection',
    'SelectionShowcase',
    'Small movements. Clear decisions.',
    'SelectionDemos',
    'switch',
  ),
  define(
    'select',
    'Select',
    'Forms',
    'Select',
    'Select',
    'SelectShowcase',
    'A familiar choice with grouped options and tactile feedback.',
    'SelectDemos',
  ),
  define(
    'autocomplete',
    'Autocomplete',
    'Forms',
    'Autocomplete',
    'Autocomplete',
    'AutocompleteShowcase',
    'Find the next choice as you type.',
    'AutocompleteDemos',
  ),
  define(
    'tabs',
    'Tabs',
    'Navigation',
    'Tabs',
    'Tabs',
    'TabsShowcase',
    'Move between views with a springy, measured indicator.',
    'TabsDemos',
  ),
  define(
    'menu',
    'Dropdown Menu',
    'Navigation',
    'Menu',
    'Menu',
    'MenuShowcase',
    'Commands, choices and nested paths, close at hand.',
    'MenuDemos',
  ),
  define(
    'stepper',
    'Stepper',
    'Navigation',
    'Stepper',
    'Stepper',
    'StepperShowcase',
    'A clear path from the first step to the last.',
    'StepperDemos',
  ),
  define(
    'accordion',
    'Accordion',
    'Navigation',
    'Accordion',
    'Accordion',
    'AccordionShowcase',
    'Let the details unfold at their own pace.',
    'AccordionDemos',
  ),
  define(
    'card',
    'Card',
    'Cards',
    'Card',
    'Card',
    'CardShowcase',
    'Composable surfaces with unmistakable depth.',
    'CardDemos',
  ),
  define(
    'bento-grid',
    'Bento Grid',
    'Cards',
    'BentoGrid',
    'BentoGrid',
    'BentoGridShowcase',
    'A little structure for your next big idea.',
    'BentoGridDemos',
  ),
  define(
    'cards-carousel',
    'Cards Carousel',
    'Cards',
    'CardsCarousel',
    'CardsCarousel',
    'CardsCarouselShowcase',
    'A tactile collection of stories to explore.',
    'CardsCarouselDemos',
  ),
  define(
    'testimonials',
    'Testimonials',
    'Cards',
    'Testimonials',
    'Testimonials',
    'TestimonialsShowcase',
    'Give good words a considered place.',
    'TestimonialsDemos',
  ),
  define(
    'badge',
    'Badge',
    'Feedback',
    'Badge',
    'Badge',
    'BadgeShowcase',
    'Compact context, considered colors and visible contours.',
    'BadgeDemos',
  ),
  define(
    'dialog',
    'Dialog',
    'Feedback',
    'Dialog',
    'Dialog',
    'DialogShowcase',
    'Make space for a focused decision.',
    'DialogDemos',
  ),
  define(
    'toast',
    'Toast',
    'Feedback',
    'Toast',
    'Toast',
    'ToastShowcase',
    'Timely confirmations, useful actions and honest outcomes.',
    'ToastDemos',
  ),
  define(
    'progress',
    'Progress',
    'Feedback',
    'Progress',
    'Progress',
    'ProgressShowcase',
    'Measured movement, from the first byte to done.',
    'ProgressDemos',
  ),
  define(
    'achievement',
    'Achievement',
    'Feedback',
    'Achievement',
    'Achievement',
    'AchievementShowcase',
    'Make progress worth keeping.',
    'AchievementDemos',
  ),
  define(
    'kinetic-type',
    'Kinetic Type',
    'Motion',
    'KineticType',
    'KineticType',
    'KineticTypeShowcase',
    'Typography with an entrance worth watching.',
    'KineticTypeDemos',
  ),
  define(
    'shuffle-deck',
    'Shuffle Deck',
    'Motion',
    'ShuffleDeck',
    'ShuffleDeck',
    'ShuffleDeckShowcase',
    'A deck of perspectives, ready for a shuffle.',
    'ShuffleDeckDemos',
  ),
  define(
    'reset-limit',
    'Reset Limit',
    'Motion',
    'ResetLimit',
    'ResetLimit',
    'ResetLimitShowcase',
    'A sculpted control with expressive reset feedback.',
    'ResetLimitDemos',
  ),
  define(
    'text-loop',
    'Text Loop',
    'Motion',
    'TextLoop',
    'TextLoop',
    'TextLoopShowcase',
    'Words with a rhythm, on sculpted ribbons.',
    'TextLoopDemos',
  ),
  define(
    'depth-carousel',
    'Depth Carousel',
    'Motion',
    'DepthCarousel',
    'DepthCarousel',
    'DepthCarouselShowcase',
    'Photographs in perspective, with room to explore.',
    'DepthCarouselDemos',
  ),
  define(
    'card-spread',
    'Card Spread',
    'Motion',
    'CardSpread',
    'CardSpread',
    'CardSpreadShowcase',
    'An open fan of photographs. Pick a perspective.',
    'CardSpreadDemos',
  ),
  define(
    'avatar',
    'Avatar',
    'Display',
    'Avatar',
    'Avatar',
    'AvatarShowcase',
    'Familiar faces in tactile frames.',
    'AvatarDemos',
  ),
  define(
    'map',
    'Map',
    'Display',
    'Map',
    'Map',
    'MapShowcase',
    'Neutral cartography with useful, tactile controls.',
    'MapDemos',
  ),
];

export const legacyCategories = { Animations: 'Motion', Other: 'Feedback' };
export const repository = 'https://github.com/gus-rlin/Duoop-UI';
export const componentHref = (entry) => `?component=${entry.id}`;
