// Public catalogue metadata stays independent of the lazy-loaded demonstrations.
const define = (
  id,
  name,
  category,
  folder,
  component,
  showcase,
  summary,
  demo,
  kind,
) => ({
  id: `builtin-${id}`,
  name,
  category,
  folder,
  component,
  showcase,
  summary,
  demo,
  kind,
  path: `src/components/${folder}/${component}.jsx`,
});

export const categories = [
  "Buttons",
  "Forms",
  "Navigation",
  "Cards",
  "Feedback",
  "Motion",
  "Display",
];
export const entries = [
  define("chart", "Chart", "Display", "Chart", "Chart", "ChartShowcase", "Data with character. Customizable curves, areas and tactile bars.", "ChartDemos"),
  define(
    "breadcrumb",
    "Breadcrumb",
    "Navigation",
    "Breadcrumb",
    "Breadcrumb",
    "BreadcrumbShowcase",
    "A clear path back. Tactile links and a distinct current location.",
    "BreadcrumbDemos",
  ),
  define(
    "separator",
    "Separator",
    "Display",
    "Separator",
    "Separator",
    "SeparatorShowcase",
    "A quiet break. Horizontal and vertical rules between related spaces.",
    "SeparatorDemos",
  ),
  define(
    "relief-button",
    "Raised button",
    "Buttons",
    "Button",
    "Button",
    "ButtonShowcase",
    "A satisfying press. Six variants, three sizes, and clear action feedback.",
    "demos/example-default",
  ),
  define(
    "reaction-button",
    "Reaction Button",
    "Buttons",
    "ReactionButton",
    "ReactionButton",
    "ReactionButtonShowcase",
    "Likes, favorites and reactions with a little personality.",
    "ReactionButtonDemos",
  ),
  define(
    "input",
    "Input",
    "Forms",
    "Forms",
    "Input",
    "FormsShowcase",
    "A considered starting point for every form.",
    "FormDemos",
    "input",
  ),
  define(
    "field",
    "Field",
    "Forms",
    "Forms",
    "Input",
    "FormsShowcase",
    "Labels, help and validation that belong together.",
    "FormDemos",
    "field",
  ),
  define(
    "input-group",
    "Input Group",
    "Forms",
    "Forms",
    "InputGroup",
    "FormsShowcase",
    "Inputs, icons and actions on one continuous surface.",
    "EnrichedDemos",
    "input-group",
  ),
  define(
    "textarea",
    "Textarea",
    "Forms",
    "Forms",
    "Textarea",
    "FormsShowcase",
    "Room for longer thoughts, with resize and character counts.",
    "EnrichedDemos",
    "textarea",
  ),
  define(
    "number-field",
    "Number Field",
    "Forms",
    "Forms",
    "NumberField",
    "FormsShowcase",
    "Precise numbers with tactile step controls.",
    "NumericDemos",
    "number-field",
  ),
  define(
    "otp-field",
    "OTP Field",
    "Forms",
    "Forms",
    "OtpField",
    "FormsShowcase",
    "Verification codes with keyboard and paste support.",
    "NumericDemos",
    "otp-field",
  ),
  define(
    "checkbox",
    "Checkbox",
    "Forms",
    "Checkbox",
    "Checkbox",
    "CheckboxShowcase",
    "One choice or a whole group. Every state feels right.",
    "CheckboxDemos",
  ),
  define(
    "radio-group",
    "Radio Group",
    "Forms",
    "Selection",
    "Selection",
    "SelectionShowcase",
    "One considered choice, from a list to a grid of cards.",
    "SelectionDemos",
    "radio",
  ),
  define(
    "switch",
    "Switch",
    "Forms",
    "Selection",
    "Selection",
    "SelectionShowcase",
    "Small movements. Clear decisions.",
    "SelectionDemos",
    "switch",
  ),
  define(
    "select",
    "Select",
    "Forms",
    "Select",
    "Select",
    "SelectShowcase",
    "A familiar choice with grouped options and tactile feedback.",
    "SelectDemos",
  ),
  define(
    "autocomplete",
    "Autocomplete",
    "Forms",
    "Autocomplete",
    "Autocomplete",
    "AutocompleteShowcase",
    "Find the next choice as you type.",
    "AutocompleteDemos",
  ),
  define(
    "tabs",
    "Tabs",
    "Navigation",
    "Tabs",
    "Tabs",
    "TabsShowcase",
    "Move between views with a springy, measured indicator.",
    "TabsDemos",
  ),
  define(
    "menu",
    "Dropdown Menu",
    "Navigation",
    "Menu",
    "Menu",
    "MenuShowcase",
    "Commands, choices and nested paths, close at hand.",
    "MenuDemos",
  ),
  define(
    "stepper",
    "Stepper",
    "Navigation",
    "Stepper",
    "Stepper",
    "StepperShowcase",
    "A clear path from the first step to the last.",
    "StepperDemos",
  ),
  define(
    "accordion",
    "Accordion",
    "Navigation",
    "Accordion",
    "Accordion",
    "AccordionShowcase",
    "Let the details unfold at their own pace.",
    "AccordionDemos",
  ),
  define(
    "card",
    "Card",
    "Cards",
    "Card",
    "Card",
    "CardShowcase",
    "Composable surfaces with unmistakable depth.",
    "CardDemos",
  ),
  define(
    "bento-grid",
    "Bento Grid",
    "Cards",
    "BentoGrid",
    "BentoGrid",
    "BentoGridShowcase",
    "A little structure for your next big idea.",
    "BentoGridDemos",
  ),
  define(
    "cards-carousel",
    "Cards Carousel",
    "Cards",
    "CardsCarousel",
    "CardsCarousel",
    "CardsCarouselShowcase",
    "A tactile collection of stories to explore.",
    "CardsCarouselDemos",
  ),
  define(
    "testimonials",
    "Testimonials",
    "Cards",
    "Testimonials",
    "Testimonials",
    "TestimonialsShowcase",
    "Give good words a considered place.",
    "TestimonialsDemos",
  ),
  define(
    "badge",
    "Badge",
    "Feedback",
    "Badge",
    "Badge",
    "BadgeShowcase",
    "Compact context, considered colors and visible contours.",
    "BadgeDemos",
  ),
  define(
    "dialog",
    "Dialog",
    "Feedback",
    "Dialog",
    "Dialog",
    "DialogShowcase",
    "Make space for a focused decision.",
    "DialogDemos",
  ),
  define(
    "toast",
    "Toast",
    "Feedback",
    "Toast",
    "Toast",
    "ToastShowcase",
    "Timely confirmations, useful actions and honest outcomes.",
    "ToastDemos",
  ),
  define(
    "progress",
    "Progress",
    "Feedback",
    "Progress",
    "Progress",
    "ProgressShowcase",
    "Measured movement, from the first byte to done.",
    "ProgressDemos",
  ),
  define(
    "achievement",
    "Achievement",
    "Feedback",
    "Achievement",
    "Achievement",
    "AchievementShowcase",
    "Make progress worth keeping.",
    "AchievementDemos",
  ),
  define(
    "kinetic-type",
    "Kinetic Type",
    "Motion",
    "KineticType",
    "KineticType",
    "KineticTypeShowcase",
    "Typography with an entrance worth watching.",
    "KineticTypeDemos",
  ),
  define(
    "shuffle-deck",
    "Shuffle Deck",
    "Motion",
    "ShuffleDeck",
    "ShuffleDeck",
    "ShuffleDeckShowcase",
    "A deck of perspectives, ready for a shuffle.",
    "ShuffleDeckDemos",
  ),
  define(
    "text-loop",
    "Text Loop",
    "Motion",
    "TextLoop",
    "TextLoop",
    "TextLoopShowcase",
    "Words with a rhythm, on sculpted ribbons.",
    "TextLoopDemos",
  ),
  define(
    "avatar",
    "Avatar",
    "Display",
    "Avatar",
    "Avatar",
    "AvatarShowcase",
    "Familiar faces in tactile frames.",
    "AvatarDemos",
  ),
  define(
    "map",
    "Map",
    "Display",
    "Map",
    "Map",
    "MapShowcase",
    "Neutral cartography with useful, tactile controls.",
    "MapDemos",
  ),

  define(
    "tooltip",
    "Tooltip",
    "Feedback",
    "Tooltip",
    "Tooltip",
    "TooltipShowcase",
    "Context at the right moment. Focus, hover, timing and collision-aware hints.",
    "TooltipDemos",
  ),
  define(
    "popover",
    "Popover",
    "Feedback",
    "Popover",
    "Popover",
    "PopoverShowcase",
    "A little more room, right next to the action. Non-modal by design.",
    "PopoverDemos",
  ),
  define(
    "slider",
    "Slider",
    "Forms",
    "Slider",
    "Slider",
    "SliderShowcase",
    "One value or a considered range. Continuous control with tactile handles.",
    "SliderDemos",
  ),
  define(
    "calendar",
    "Calendar",
    "Forms",
    "Calendar",
    "Calendar",
    "CalendarShowcase",
    "A day to remember. Standalone single-date and range selection.",
    "CalendarDemos",
  ),
  define(
    "date-picker",
    "Date Picker",
    "Forms",
    "DatePicker",
    "DatePicker",
    "DatePickerShowcase",
    "Make a date. A field, a popover and a calendar working together.",
    "DatePickerDemos",
  ),
  define(
    "table",
    "Table",
    "Display",
    "Table",
    "Table",
    "TableShowcase",
    "The work, at a glance. Semantic tables and useful data interactions.",
    "TableDemos",
  ),
  define(
    "pagination",
    "Pagination",
    "Navigation",
    "Pagination",
    "Pagination",
    "PaginationShowcase",
    "One page at a time. A clear path through larger collections.",
    "PaginationDemos",
  ),
  define(
    "sheet",
    "Sheet",
    "Feedback",
    "Sheet",
    "Sheet",
    "SheetShowcase",
    "Bring the details in. A focused panel from any side of the screen.",
    "SheetDemos",
  ),
  define(
    "file-upload",
    "File Upload",
    "Forms",
    "FileUpload",
    "FileUpload",
    "FileUploadShowcase",
    "A place for your files. Drop, preview, retry and keep moving.",
    "FileUploadDemos",
  ),
  define(
    "skeleton",
    "Skeleton",
    "Feedback",
    "Skeleton",
    "Skeleton",
    "SkeletonShowcase",
    "Keep the shape of what comes next. Quiet structural loading states.",
    "SkeletonDemos",
  ),
  define(
    "alert",
    "Alert",
    "Feedback",
    "Alert",
    "Alert",
    "AlertShowcase",
    "A message that stays. Clear context, useful actions and considered tones.",
    "AlertDemos",
  ),
  define("folder", "Folder", "Cards", "Folder", "Folder", "FolderShowcase", "A tabbed folder that unfolds into selectable documents.", "FolderDemos"),
];

export const legacyCategories = { Animations: "Motion", Other: "Feedback" };
export const repository = "https://github.com/gus-rlin/Duoop-UI";
export const componentHref = (entry) => `?component=${entry.id}`;
