import React, { createContext, useContext, useEffect, useId, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useAnchoredOverlay } from '../useAnchoredOverlay';
import './Menu.css';
import './MenuPortal.css';

const MenuContext = createContext(null);
export function Menu({ trigger, children, open: controlled, defaultOpen = false, onOpenChange, placement = 'bottom-start', openOnHover = false, label = 'Menu' }) {
  const [internal, setInternal] = useState(defaultOpen); const open = controlled ?? internal; const root = useRef(null); const button = useRef(null); const position = useRef(null); const popup = useRef(null); const hoverTimer = useRef(null); const id = useId();
  const setOpen = next => { if (controlled === undefined) setInternal(next); onOpenChange?.(next); };
  const anchored = useAnchoredOverlay({ open, anchorRef: button, overlayRef: position, placement, gap: 8, minimumWidth: 230 });
  useEffect(() => { if (!open) return; const outside = event => { const insideSubmenu=event.composedPath().some(node=>node.classList?.contains('duoop-menu__subpopup')); if (!root.current?.contains(event.target) && !position.current?.contains(event.target) && !insideSubmenu) setOpen(false); }; document.addEventListener('pointerdown', outside); return () => document.removeEventListener('pointerdown', outside); }, [open]);
  useEffect(() => { if (!open) return; const closeOnExternalGesture = event => { if (!position.current?.contains(event.target) && !event.composedPath().some(node=>node.classList?.contains('duoop-menu__subpopup'))) setOpen(false); }; document.addEventListener('wheel', closeOnExternalGesture, { capture: true, passive: true }); document.addEventListener('touchmove', closeOnExternalGesture, { capture: true, passive: true }); return () => { document.removeEventListener('wheel', closeOnExternalGesture, true); document.removeEventListener('touchmove', closeOnExternalGesture, true); }; }, [open]);
  function focusAt(index) { const items = [...popup.current.querySelectorAll('[role^=menuitem]:not([aria-disabled=true])')]; items[(index + items.length) % items.length]?.focus(); }
  function keys(event) { const items = [...popup.current.querySelectorAll('[role^=menuitem]:not([aria-disabled=true])')]; const index = items.indexOf(document.activeElement); if (event.key === 'Escape') { event.preventDefault(); setOpen(false); button.current.focus(); } else if (['ArrowDown','ArrowUp','Home','End'].includes(event.key)) { event.preventDefault(); focusAt(event.key === 'Home' ? 0 : event.key === 'End' ? items.length - 1 : index + (event.key === 'ArrowDown' ? 1 : -1)); } else if (event.key.length === 1 && /\S/.test(event.key)) { const next = items.find(item => item.textContent.trim().toLowerCase().startsWith(event.key.toLowerCase())); next?.focus(); } }
  const context = { close: () => { setOpen(false); button.current?.focus(); } };
  const cancelHoverClose = () => clearTimeout(hoverTimer.current);
  const scheduleHoverClose = () => { if (openOnHover) { cancelHoverClose(); hoverTimer.current = setTimeout(() => setOpen(false), 120); } };
  useEffect(() => cancelHoverClose, []);
  return <MenuContext.Provider value={context}><div ref={root} className="duoop-menu" onPointerEnter={() => { if (openOnHover) { cancelHoverClose(); setOpen(true); } }} onPointerLeave={scheduleHoverClose}><button ref={button} className="duoop-menu__trigger" type="button" aria-haspopup="menu" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)} onKeyDown={event => { if (['ArrowDown','Enter',' '].includes(event.key) && !open) { event.preventDefault(); setOpen(true); requestAnimationFrame(() => focusAt(0)); } }}>{trigger}</button>{open && createPortal(<div ref={position} className={`duoop-menu__position duoop-menu__position--${anchored.resolvedPlacement}`} style={anchored.style} onPointerEnter={cancelHoverClose} onPointerLeave={scheduleHoverClose}><div ref={popup} id={id} className="duoop-menu__popup" role="menu" aria-label={label} onKeyDown={keys}>{children}</div></div>, document.body)}</div></MenuContext.Provider>;
}
export function MenuItem({ children, icon, shortcut, description, disabled = false, destructive = false, href, keepOpen = false, onSelect, role = 'menuitem', checked }) {
  const menu = useContext(MenuContext); const Component = href ? 'a' : 'button';
  return <Component className="duoop-menu__item" {...(href ? { href } : { type:'button' })} role={role} aria-checked={role === 'menuitem' ? undefined : checked} aria-disabled={disabled || undefined} tabIndex={disabled ? -1 : 0} data-destructive={destructive || undefined} onClick={event => { if (disabled) { event.preventDefault(); return; } onSelect?.(event); if (!keepOpen) menu.close(); }}>
    <span className="duoop-menu__mark" aria-hidden="true">{role !== 'menuitem' && (checked ? <svg viewBox="0 0 20 20"><path d="m4 10 4 4 8-9" /></svg> : null)}{icon}</span><span className="duoop-menu__copy"><strong>{children}</strong>{description && <small>{description}</small>}</span>{shortcut && <kbd>{shortcut}</kbd>}
  </Component>;
}
export function MenuLabel({children}){return <div className="duoop-menu__label">{children}</div>}
export function MenuSeparator(){return <div className="duoop-menu__separator" role="separator"/>}
export function MenuSubmenu({ label, icon, children }) {
  const [open,setOpen]=useState(false); const button=useRef(null); const position=useRef(null); const timer=useRef(null); const anchored=useAnchoredOverlay({open,anchorRef:button,overlayRef:position,placement:'right-start',gap:6,minimumWidth:210}); const cancel=()=>clearTimeout(timer.current); const closeLater=()=>{cancel();timer.current=setTimeout(()=>setOpen(false),120)}; useEffect(()=>cancel,[]);
  function submenuKeys(event){const items=[...position.current.querySelectorAll('[role^=menuitem]:not([aria-disabled=true])')];const index=items.indexOf(document.activeElement);if(event.key==='ArrowLeft'){event.preventDefault();event.stopPropagation();setOpen(false);button.current?.focus()}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();event.stopPropagation();const next=event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length;items[next]?.focus()}}
  return <div className="duoop-menu__submenu" onPointerEnter={()=>{cancel();setOpen(true)}} onPointerLeave={closeLater}><button ref={button} type="button" role="menuitem" className="duoop-menu__item" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(true)} onKeyDown={event=>{if(event.key==='ArrowRight'){event.preventDefault();setOpen(true);requestAnimationFrame(()=>position.current?.querySelector('[role^=menuitem]')?.focus())}}}><span className="duoop-menu__mark">{icon}</span><span className="duoop-menu__copy"><strong>{label}</strong></span><span aria-hidden="true">›</span></button>{open&&createPortal(<div ref={position} className="duoop-menu__subpopup" style={anchored.style} role="menu" aria-label={label} onPointerEnter={cancel} onPointerLeave={closeLater} onKeyDown={submenuKeys}>{children}</div>,document.body)}</div>
}
