import { openCatalog } from './catalog-page.mjs';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless:true });
const page = await browser.newPage({ viewport:{ width:1440, height:1000 } });
const base = process.env.TEST_URL || 'http://127.0.0.1:5176';
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const card = title => page.getByRole('article', { name:`Autocomplete: ${title}`, exact:true });
async function contained() {
  const box = await page.locator('.autocomplete-popup').boundingBox();
  const viewport = page.viewportSize();
  assert.ok(box && box.x >= 0 && box.y >= 0 && box.x + box.width <= viewport.width && box.y + box.height <= viewport.height);
}
try {
  await openCatalog(page, `${base}/?component=builtin-autocomplete`);
  await page.getByRole('heading', { name:'Autocomplete', exact:true }).waitFor();
  assert.equal(await page.locator('.gallery-card').count(), 12);
  const input = card('Default').getByRole('combobox');
  await input.fill('fi');
  assert.equal(await page.getByRole('option').count(), 1);
  await input.press('ArrowDown');
  await input.press('Enter');
  assert.equal(await input.inputValue(), 'Figma');
  assert.equal(await input.getAttribute('aria-expanded'), 'false');
  await input.fill('My own tool'); await input.press('Escape');
  assert.equal(await input.inputValue(), 'My own tool');
  await input.fill(''); await input.press('ArrowDown'); await input.press('ArrowDown'); await input.press('ArrowDown');
  assert.equal(await page.getByRole('option', { selected:true }).innerText(), 'GitHub');
  await input.press('Tab'); assert.equal(await input.getAttribute('aria-expanded'), 'false');
  await card('Clear and trigger').getByRole('button', { name:'Show Tool suggestions' }).click();
  await page.getByRole('option', { name:'Framer', exact:true }).click();
  await card('Clear and trigger').getByRole('button', { name:'Clear Tool' }).click();
  assert.equal(await card('Clear and trigger').getByRole('combobox').inputValue(), '');
  await card('Clear and trigger').getByRole('combobox').press('Escape');
  await card('Auto highlight').getByRole('combobox').fill('fr');
  await card('Auto highlight').getByRole('combobox').press('Enter');
  assert.equal(await card('Auto highlight').getByRole('combobox').inputValue(), 'Framer');
  const controlled = card('Controlled value');
  await controlled.getByRole('combobox').fill('Personal tool');
  await controlled.getByRole('button', { name:'Reset value' }).click();
  assert.equal(await controlled.getByRole('combobox').inputValue(), '');
  assert.equal(await card('Disabled').getByRole('combobox').isDisabled(), true);
  const form = card('Form validation');
  await form.getByRole('button', { name:'Save preference' }).click();
  assert.equal(await form.getByRole('combobox').getAttribute('aria-invalid'), 'true');
  assert.equal(await form.getByRole('combobox').evaluate(el => el === document.activeElement), true);
  await form.getByRole('combobox').fill('Paper');
  await form.getByRole('combobox').press('Escape');
  await form.getByRole('button', { name:'Save preference' }).click();
  assert.equal(await form.locator('[data-status=success]').count(), 1);
  await form.getByRole('combobox').fill('Notebook');
  assert.equal(await form.locator('[data-status=success]').count(), 0);
  const city = card('Long list').getByRole('combobox');
  await city.fill('montreal'); assert.equal(await page.getByRole('option').innerText(), 'Montréal');
  await city.fill(''); await city.press('ArrowUp');
  assert.equal(await page.getByRole('option', { selected:true }).innerText(), 'Zürich');
  await contained(); await city.press('Escape');
  await card('Grouped suggestions').getByRole('combobox').click();
  assert.equal(await page.getByRole('group', { name:'Development', exact:true }).count(), 1);
  await contained();
  await page.waitForTimeout(250);
  await page.screenshot({ path:'artifacts/autocomplete-desktop.png' });
  await card('Grouped suggestions').getByRole('combobox').press('Escape');
  await card('Default').getByRole('button', { name:/View code/ }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox').fill('fi');
  assert.equal(await dialog.locator('.autocomplete-popup').count(), 1);
  await dialog.getByRole('option', { name:'Figma' }).click();
  await dialog.getByRole('combobox').press('Escape');
  assert.equal(await dialog.isVisible(), false);
  for (const width of [1024,390]) {
    await page.setViewportSize({ width, height:844 });
    await card('Default').getByRole('combobox').fill('');
    await card('Default').getByRole('combobox').click();
    await contained();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.waitForTimeout(250);
    assert.ok(Math.abs((await page.locator('.autocomplete-popup').boundingBox()).width - (await card('Default').locator('.autocomplete-control').boundingBox()).width) < 1);
    await page.screenshot({ path:`artifacts/autocomplete-${width}.png` });
    await card('Default').getByRole('combobox').press('Escape');
  }
  await page.emulateMedia({ reducedMotion:'reduce' });
  await input.click();
  assert.equal(await page.locator('.autocomplete-popup').evaluate(el => getComputedStyle(el).animationName), 'none');
  await openCatalog(page, base);
  await page.getByRole('link', { name:'Explore Autocomplete', exact:true }).waitFor();
  assert.equal(await page.locator('.catalog-preview--autocomplete').count(), 1);
  assert.deepEqual(errors, []);
  console.log('PASS: Autocomplete filtering, free text, keyboard, disabled options, clear, controlled value, validation, groups, accents, portal in dialog, responsive layout, reduced motion, catalogue.');
} finally { await browser.close(); }
