import { openCatalog } from './catalog-page.mjs';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless:true });
const page = await browser.newPage({ viewport:{ width:1440, height:1100 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await openCatalog(page, process.env.TEST_URL || 'http://127.0.0.1:5176');
  assert.ok(await page.locator('.catalog-card-preview-link').count() >= 30);
  await page.getByRole('link', { name:'Explore Cards Carousel', exact:true }).click();
  const lab = page.getByRole('region', { name:'Cards Carousel playground', exact:true });
  const collection = lab.getByRole('region', { name:'Studio stories', exact:true });
  const cards = collection.locator('.cards-carousel__card');
  await cards.first().locator('img').waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll('.cards-playground img')].every(img => img.complete && img.naturalWidth > 0));
  assert.ok(await collection.getByRole('button', { name:'Previous cards' }).isDisabled());
  await collection.getByRole('button', { name:'Next cards' }).click();
  await page.waitForTimeout(600);
  assert.ok(await collection.locator('.cards-carousel__rail').evaluate(node => node.scrollLeft > 100));
  await cards.first().focus();
  await cards.first().press('End');
  assert.ok(await cards.last().evaluate(node => node === document.activeElement));
  await page.waitForTimeout(100);
  assert.ok(await collection.getByRole('button', { name:'Next cards' }).isDisabled());
  await cards.last().press('Home');
  await cards.first().press('Enter');
  const modal = page.getByRole('dialog', { name:'Find a different point of view.' });
  await modal.waitFor();
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden');
  await modal.getByRole('button', { name:'Close story' }).press('Tab');
  assert.ok(await modal.evaluate(node => node.contains(document.activeElement)));
  await page.waitForTimeout(300);
  await page.screenshot({ path:'artifacts/cards-carousel-detail.png' });
  assert.ok(await modal.getByRole('button', { name:'Previous story', exact:true }).isDisabled());
  await modal.getByRole('button', { name:'Next story', exact:true }).click();
  const secondStory = page.getByRole('dialog', { name:'Make room for what matters.', exact:true });
  await secondStory.waitFor();
  assert.ok(await secondStory.getByRole('heading', { level:2 }).evaluate(node => node === document.activeElement));
  assert.equal(await secondStory.evaluate(node => node.scrollTop), 0);
  assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden');
  await secondStory.getByRole('button', { name:'Previous story', exact:true }).click();
  await page.keyboard.press('Escape');
  await modal.waitFor({ state:'hidden' });
  assert.ok(await cards.first().evaluate(node => node === document.activeElement));
  assert.equal(await page.evaluate(() => document.body.style.overflow), '');
  await lab.screenshot({ path:'artifacts/cards-carousel-desktop.png' });
  await lab.getByRole('button', { name:'Dark', exact:true }).click();
  await cards.first().click();
  assert.equal(await modal.evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(37, 35, 35)');
  await modal.getByRole('button', { name:'Back to collection' }).click();
  await lab.screenshot({ path:'artifacts/cards-carousel-dark.png' });
  await lab.getByRole('button', { name:'Light', exact:true }).click();
  for (const width of [1000,768,390,320]) {
    await page.setViewportSize({ width, height:1000 });
    await cards.first().press('Home');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No page overflow at ${width}`);
    if (width === 390) { await page.mouse.move(0,0); await page.waitForTimeout(250); await lab.screenshot({ path:'artifacts/cards-carousel-mobile.png' }); }
    await cards.first().click();
    assert.ok(await modal.evaluate(node => node.scrollWidth <= node.clientWidth), `Modal fits at ${width}`);
    if (width === 390) { await page.waitForTimeout(300); await modal.screenshot({ path:'artifacts/cards-carousel-detail-mobile.png' }); }
    await page.keyboard.press('Escape');
  }
  await page.emulateMedia({ reducedMotion:'reduce' });
  await cards.first().press('ArrowRight');
  assert.ok(await cards.nth(1).evaluate(node => node === document.activeElement));
  const single = page.getByRole('region', { name:'Single story', exact:true });
  assert.ok(await single.getByRole('button', { name:'Next cards' }).isDisabled());
  await single.getByRole('button', { name:/^Read / }).click();
  const singleModal = page.getByRole('dialog', { name:'Find a different point of view.' });
  assert.ok(await singleModal.getByRole('button', { name:'Next story', exact:true }).isDisabled());
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width:1440, height:1100 });
  await page.getByRole('button', { name:'View code: Cards Carousel Compact cards', exact:true }).click();
  const example = page.getByRole('dialog', { name:'Compact cards', exact:true });
  await example.getByRole('button', { name:'Read Find a different point of view.', exact:true }).click();
  await page.keyboard.press('Escape');
  assert.ok(await example.isVisible());
  await example.getByRole('button', { name:'Close example' }).click();
  assert.deepEqual(errors, []);
  console.log('Cards Carousel: catalogue, scroll, keyboard, modal, focus, dark, responsive, nested dialog and reduced motion passed.');
} finally { await browser.close(); }
