import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(`${process.env.TEST_URL || 'http://127.0.0.1:5173'}/?component=builtin-chart`);
  const playground = page.locator('.chart-playground');
  await playground.waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(600);
  const plot = playground.getByRole('group', { name: 'Explore chart' });
  await plot.focus();
  await page.keyboard.press('End');
  assert.match(await playground.locator('.duoop-chart__footer output').innerText(), /Aug.*Studio: 92/s);
  await page.keyboard.press('Home');
  assert.match(await playground.locator('.duoop-chart__footer output').innerText(), /Jan.*24/s);
  await page.keyboard.press('Escape');
  await playground.getByRole('checkbox', { name: 'Compare series' }).check();
  const studio = playground.getByRole('button', { name: 'Studio', exact: true });
  await studio.click();
  assert.equal(await studio.getAttribute('aria-pressed'), 'false');
  await playground.getByRole('button', { name: 'Shop', exact: true }).click();
  assert.equal(await playground.getByText('Select a series to explore').count(), 1);
  await studio.click();
  await playground.getByRole('button', { name: 'Bar', exact: true }).click();
  assert.equal(await playground.locator('.duoop-chart__marks rect').count(), 16);
  await playground.getByText('View data table', { exact: true }).click();
  assert.equal(await playground.locator('tbody tr').count(), 8);
  await playground.getByRole('button', { name: 'Reset', exact: true }).click();
  assert.equal(await playground.locator('details').getAttribute('open'), null);
  await page.waitForTimeout(500);
  await playground.screenshot({ path: 'artifacts/chart-playground-desktop.png' });
  await playground.getByRole('checkbox', { name: 'Compare series' }).check();
  const dataButton = playground.getByRole('button', { name: 'Our data', exact: true });
  await dataButton.click();
  const editor = page.getByRole('dialog', { name: 'Our data', exact: true });
  await editor.getByRole('textbox', { name: 'Label 1', exact: true }).fill('Launch');
  await editor.getByRole('spinbutton', { name: 'Studio 1', exact: true }).fill('-12.5');
  await editor.getByRole('spinbutton', { name: 'Studio 2', exact: true }).fill('');
  await page.keyboard.press('Escape');
  await dataButton.focus();
  await page.keyboard.press('Enter');
  assert.equal(await editor.getByRole('textbox', { name: 'Label 1', exact: true }).inputValue(), 'Launch', 'Closing preserves the draft');
  await editor.getByRole('button', { name: 'Add row', exact: true }).click();
  await editor.getByRole('textbox', { name: 'Label 9', exact: true }).fill('Sep');
  await editor.getByRole('spinbutton', { name: 'Studio 9', exact: true }).fill('104');
  await editor.getByRole('spinbutton', { name: 'Shop 9', exact: true }).fill('60');
  await editor.getByRole('button', { name: 'Remove row 3', exact: true }).click();
  await editor.locator('.chart-data-editor__rows').evaluate(node => { node.scrollTop = 0; });
  await editor.screenshot({ path: 'artifacts/chart-data-editor-desktop.png' });
  const editorAudit = await new AxeBuilder({ page }).include('.chart-data-editor').analyze();
  assert.deepEqual(editorAudit.violations.map(item => item.id), []);
  await editor.getByRole('button', { name: 'Apply data', exact: true }).click();
  await playground.getByText('View data table', { exact: true }).click();
  assert.match(await playground.locator('tbody tr').first().innerText(), /Launch.*-12.5/s);
  assert.match(await playground.locator('tbody tr').nth(1).innerText(), /Feb.*—/s);
  assert.match(await playground.locator('tbody tr').last().innerText(), /Sep.*104.*60/s);
  assert.equal(await playground.locator('tbody tr').count(), 8);
  await playground.getByRole('button', { name: 'Reset', exact: true }).click();
  await dataButton.click();
  assert.equal(await editor.getByRole('textbox', { name: 'Label 1', exact: true }).inputValue(), 'Jan');
  await page.keyboard.press('Escape');
  const bars = page.getByRole('article', { name: 'Chart: One month at a time', exact: true });
  assert.equal(await bars.locator('.duoop-chart__plot svg').evaluate(svg => {
    const baseline = Number(svg.querySelector(':scope > path').getAttribute('d').match(/,([\d.]+)H/)[1]);
    return [...svg.querySelectorAll('.duoop-chart__marks rect')].every(rect =>
      Number(rect.getAttribute('y')) + Number(rect.getAttribute('height')) < baseline - 1);
  }), true, 'Positive bars and their shadows clear the baseline');
  await bars.screenshot({ path: 'artifacts/chart-bars-desktop.png' });
  const missing = page.getByRole('article', { name: 'Chart: A missing chapter', exact: true });
  assert.equal(await missing.locator('.duoop-chart__marks path').count(), 4, 'Missing value splits line into two segments');
  const negative = page.getByRole('article', { name: 'Chart: Above and below', exact: true });
  assert.equal(await negative.locator('rect[height]').evaluateAll(nodes => nodes.every(node => Number(node.getAttribute('height')) >= 0)), true);
  const audit = await new AxeBuilder({ page }).include('.chart-playground').analyze();
  assert.deepEqual(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) })), []);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForTimeout(300);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'No mobile page overflow');
  assert.equal(await playground.locator('.duoop-chart__marks').evaluate(node => getComputedStyle(node).animationName), 'none');
  await playground.screenshot({ path: 'artifacts/chart-playground-mobile.png' });
  await dataButton.click();
  await editor.screenshot({ path: 'artifacts/chart-data-editor-mobile.png' });
  const editorBounds = await editor.boundingBox();
  assert.ok(editorBounds.x >= 0 && editorBounds.x + editorBounds.width <= 390, 'Data bubble fits mobile');
  assert.equal(await editor.evaluate(node => node.scrollWidth <= node.clientWidth), true, 'No editor horizontal overflow');
  const applyBounds = await editor.getByRole('button', { name: 'Apply data', exact: true }).boundingBox();
  assert.ok(applyBounds.y >= editorBounds.y && applyBounds.y + applyBounds.height <= editorBounds.y + editorBounds.height, 'Apply remains visible on mobile');
  await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
  console.log('PASS chart: keyboard, series toggles, bar spacing, table, data editing, draft retention, missing and negative values, reset, accessibility, mobile and reduced motion.');
} finally {
  await browser.close();
}
