import { openCatalog } from './catalog-page.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless:true });
const page = await browser.newPage({ viewport:{ width:1440,height:1000 }, permissions:['clipboard-read','clipboard-write'] });
const base = process.env.TEST_URL || 'http://127.0.0.1:5176';
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const card = (kind,title) => page.getByRole('article',{ name:`${kind}: ${title}`,exact:true });
const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'The page must fit its viewport');
await mkdir('artifacts', { recursive:true });
try {
  await openCatalog(page, base);
  for (const name of ['Stepper','Reaction Button']) assert.equal(await page.getByRole('link', { name:`Explore ${name}`,exact:true }).count(),1);
  await page.locator('.catalog-grid').screenshot({ path:'artifacts/experience-library.png' });
  await openCatalog(page, `${base}/?component=builtin-stepper`);
  assert.equal(await page.locator('.gallery-card').count(),22);
  const numbered = card('Stepper','Numbered journey');
  assert.equal(await numbered.locator('[data-step=ready]').isDisabled(),true);
  await numbered.getByRole('button',{ name:'Continue',exact:true }).click();
  assert.equal(await numbered.locator('[data-step=ready]').getAttribute('aria-current'),'step');
  assert.equal(await numbered.locator('[data-step=workspace]').locator('..').getAttribute('data-state'),'complete');
  await numbered.getByRole('button',{ name:'Finish setup',exact:true }).click();
  await numbered.getByText('Your workspace is ready for its first idea.',{ exact:true }).waitFor();
  await numbered.getByRole('button',{ name:'Reset',exact:true }).click();
  const free = card('Stepper','Free navigation');
  await free.locator('[data-step=profile]').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await free.locator('[data-step=workspace]').evaluate(el => el === document.activeElement),true);
  await page.keyboard.press('End');
  await page.keyboard.press('Enter');
  assert.equal(await free.locator('[data-step=ready]').getAttribute('aria-current'),'step');
  const validation = card('Stepper','Validation and error');
  await validation.getByRole('button',{ name:'Continue',exact:true }).click();
  await validation.locator('[data-state=error]').waitFor();
  assert.equal(await validation.locator('[data-step=workspace]').getAttribute('aria-current'),'step');
  await validation.getByRole('checkbox',{ name:'I have reviewed the workspace settings' }).check();
  await validation.getByRole('button',{ name:'Continue',exact:true }).click();
  await validation.locator('[data-step=ready][aria-current=step]').waitFor();
  const optional = card('Stepper','Optional step');
  await optional.getByRole('button',{ name:'Skip for now',exact:true }).click();
  assert.equal(await optional.locator('[data-step=workspace]').locator('..').getAttribute('data-state'),'skipped');
  await optional.getByRole('button',{ name:'Back',exact:true }).click();
  await optional.getByRole('button',{ name:'Continue',exact:true }).click();
  assert.equal(await optional.locator('[data-step=workspace]').locator('..').getAttribute('data-state'),'complete');
  const conditional = card('Stepper','Conditional journey');
  await conditional.getByRole('switch',{ name:'This is a team workspace' }).check();
  assert.equal(await conditional.locator('[data-step=team]').count(),1);
  await conditional.getByRole('button',{ name:'Continue',exact:true }).click();
  assert.equal(await conditional.locator('[data-step=team]').getAttribute('aria-current'),'step');
  const condensed = card('Stepper','Long condensed journey');
  assert.equal(await condensed.locator('[data-step]').count(),4);
  await condensed.getByRole('button',{ name:/Show .* hidden steps/ }).click();
  assert.equal(await condensed.locator('[data-step]').count(),7);
  await page.getByRole('region',{ name:'Stepper playground' }).screenshot({ path:'artifacts/stepper-desktop.png' });
  await noOverflow();

  await openCatalog(page, `${base}/?component=builtin-reaction-button`);
  assert.equal(await page.locator('.gallery-card').count(),25);
  const initialReactions = card('Reaction Button','Initial loading');
  assert.equal(await initialReactions.locator('.reaction-button').count(),0);
  await initialReactions.getByRole('button',{ name:'Load reactions',exact:true }).click();
  await initialReactions.locator('.duoop-reaction[data-state=loading]').waitFor();
  assert.equal(await initialReactions.locator('.reaction-separate-count').innerText(),'—');
  assert.equal(await initialReactions.locator('.reaction-separate-count').getAttribute('aria-label'),'Loading reactions');
  await initialReactions.getByRole('button',{ name:'Like, 1,248 reactions',exact:true }).waitFor();
  const like = card('Reaction Button','Like with count');
  await like.getByRole('button',{ name:'Like, 24 reactions',exact:true }).click();
  assert.equal(await like.getByRole('button',{ name:'Liked, 25 reactions',exact:true }).getAttribute('aria-pressed'),'true');
  await like.getByRole('button',{ name:'Liked, 25 reactions',exact:true }).click();
  assert.equal(await like.getByRole('button',{ name:'Like, 24 reactions',exact:true }).getAttribute('aria-pressed'),'false');
  const quota = card('Reaction Button','Contribution limit');
  await quota.locator('.reaction-button').click({ clickCount:5,delay:40 });
  assert.equal(await quota.locator('.reaction-button').isDisabled(),true);
  assert.match(await quota.innerText(),/3 of 3 contributions used/);
  assert.match(await quota.locator('.reaction-count').innerText(),/27/);
  const exclusive = card('Reaction Button','Exclusive choices');
  await exclusive.locator('.reaction-button').nth(0).click();
  await exclusive.locator('.reaction-button').nth(1).click();
  assert.equal(await exclusive.locator('[aria-pressed=true]').count(),1);
  const rollback = card('Reaction Button','Optimistic rollback');
  await rollback.locator('.reaction-button').click();
  assert.match(await rollback.locator('.reaction-separate-count').innerText(),/1,249/);
  await rollback.locator('[data-state=error]').waitFor();
  assert.match(await rollback.locator('.reaction-separate-count').innerText(),/1,248/);
  await rollback.getByRole('switch',{ name:'Simulate a failed save' }).uncheck();
  await rollback.locator('.reaction-button').click();
  await rollback.locator('[data-state=selected]').waitFor();
  assert.match(await rollback.locator('.reaction-separate-count').innerText(),/1,249/);
  const confirmed = card('Reaction Button','Confirmed update');
  await confirmed.locator('.reaction-button').click();
  assert.match(await confirmed.locator('.reaction-separate-count').innerText(),/1,248/);
  await confirmed.locator('[data-state=selected]').waitFor();
  assert.match(await confirmed.locator('.reaction-separate-count').innerText(),/1,249/);
  const add = card('Reaction Button','Add reaction');
  await add.getByRole('button',{ name:'Add reaction',exact:true }).click();
  const picker = page.getByRole('dialog',{ name:'Choose a reaction' });
  await picker.getByRole('button',{ name:'Great idea',exact:true }).click();
  assert.equal(await add.getByRole('button',{ name:/Inspired|Celebrated/ }).count(),1);
  await add.getByRole('button',{ name:'Add reaction',exact:true }).click();
  await page.keyboard.press('End');
  assert.equal(await picker.getByRole('button',{ name:'Thank you' }).evaluate(el => el === document.activeElement),true);
  await page.keyboard.press('Escape');
  assert.equal(await add.getByRole('button',{ name:'Add reaction',exact:true }).evaluate(el => el === document.activeElement),true);
  const summary = card('Reaction Button','Collective summary');
  await summary.getByRole('button',{ name:/View people/ }).click();
  const detail = page.getByRole('dialog',{ name:'People who reacted' });
  assert.equal(await detail.locator('.reaction-details li').count(),4);
  await detail.getByRole('button',{ name:'Like',exact:true }).click();
  assert.equal(await detail.locator('.reaction-details li').count(),2);
  await page.keyboard.press('Escape');
  const auth = card('Reaction Button','Sign in required');
  await auth.locator('.reaction-button').click();
  assert.equal(await auth.locator('.reaction-button').getAttribute('aria-pressed'),'false');
  await auth.getByRole('button',{ name:'Use demo account' }).click();
  await auth.locator('.reaction-button').click();
  assert.equal(await auth.locator('.reaction-button').getAttribute('aria-pressed'),'true');
  await page.getByRole('region',{ name:'Reaction Button playground' }).screenshot({ path:'artifacts/reaction-desktop.png' });
  await noOverflow();

  for (const width of [1000,768,390,320]) {
    await page.setViewportSize({ width,height:900 });
    for (const [id,count] of [['stepper',22],['reaction-button',25]]) {
      await openCatalog(page, `${base}/?component=builtin-${id}`);
      assert.equal(await page.locator('.gallery-card').count(),count);
      await noOverflow();
      if (width === 390) await page.locator('.feedback-lab').screenshot({ path:`artifacts/${id}-mobile.png` });
    }
  }
  await page.emulateMedia({ reducedMotion:'reduce' });
  await openCatalog(page, `${base}/?component=builtin-reaction-button`);
  await card('Reaction Button','Like with count').locator('.reaction-button').click();
  assert.equal(await card('Reaction Button','Like with count').locator('.reaction-particles').evaluate(el => getComputedStyle(el).display),'none');
  assert.deepEqual(errors,[]);
  console.log('Passed: 47 examples, journeys, reactions, responsive layouts and reduced motion.');
} finally { await browser.close(); }
