import { openCatalog } from './catalog-page.mjs';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width:1440, height:1050 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const url = process.env.TEST_URL || 'http://127.0.0.1:5176';
const loaded = () => page.waitForFunction(() => [...document.querySelectorAll('.leaflet-tile')].some(tile => tile.complete && tile.naturalWidth > 0));
try {
  await openCatalog(page, `${url}/?component=builtin-map`);
  await loaded();
  assert.equal(await page.locator('.duoop-map').count(), 1);
  assert.equal(await page.locator('.leaflet-marker-icon, .leaflet-overlay-pane path, .map-place').count(), 0);
  const map = page.getByRole('region', { name:'New York map', exact:true });
  const tile = page.locator('.leaflet-tile').first();
  assert.match(await tile.getAttribute('src'), /\/12\/1206\/1539\.png/);
  const paneTransform = () => page.locator('.leaflet-map-pane').evaluate(el => el.style.transform);
  const before = await paneTransform();
  await map.scrollIntoViewIfNeeded();
  const box = await map.boundingBox();
  await page.mouse.move(box.x + 200, box.y + 250);
  await page.mouse.down();
  await page.mouse.move(box.x + 300, box.y + 260, { steps:10 });
  await page.mouse.up();
  await page.waitForTimeout(500);
  assert.notEqual(await paneTransform(), before);
  await page.getByRole('button', { name:'Zoom in', exact:true }).click();
  await page.waitForTimeout(500);
  assert.ok(await page.locator('.leaflet-tile[src*="/13/"]').count() > 0);
  assert.equal(await page.locator('.duoop-map-readout strong').textContent(), '13');
  await page.getByRole('button', { name:'Reset view', exact:true }).click();
  await page.waitForTimeout(700);
  assert.equal(await page.locator('.duoop-map-readout strong').textContent(), '12');
  await map.focus();
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(400);
  await page.getByRole('button', { name:'Reset view', exact:true }).click();
  await page.mouse.move(10, 10);
  await page.locator('.map-atlas').scrollIntoViewIfNeeded();
  await page.waitForTimeout(700);
  await page.screenshot({ path:'artifacts/map-neutral-desktop.png' });
  for (const width of [900, 390]) {
    await page.setViewportSize({ width, height:950 });
    await page.locator('.map-atlas').scrollIntoViewIfNeeded();
    await page.waitForTimeout(500);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path:`artifacts/map-neutral-${width}.png` });
  }
  await page.emulateMedia({ reducedMotion:'reduce' });
  await page.getByRole('button', { name:'Zoom out', exact:true }).click();
  await page.getByRole('button', { name:'Reset view', exact:true }).click();
  await page.getByRole('button', { name:'View code: Map New York', exact:true }).click();
  await page.getByRole('dialog').locator('pre').waitFor();
  await page.getByRole('button', { name:'Close example', exact:true }).click();
  await page.route('**/tile.openstreetmap.org/**', route => route.abort());
  await page.reload();
  await page.locator('.duoop-map-message[role=alert]').waitFor();
  await page.unroute('**/tile.openstreetmap.org/**');
  await page.getByRole('button', { name:'Retry', exact:true }).click();
  await loaded();
  await openCatalog(page, url);
  await page.locator('.catalog-preview--map').scrollIntoViewIfNeeded();
  await page.screenshot({ path:'artifacts/map-neutral-catalog.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: single neutral New York map; no markers or routes; pan, zoom, reset, keyboard, responsive layouts, reduced motion, dialog and retry.');
} finally { await browser.close(); }
