import { openCatalog } from './catalog-page.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const card = (kind, title) => page.getByRole('article', { name: `${kind}: ${title}`, exact: true });
const base = process.env.TEST_URL || 'http://127.0.0.1:5176';
await mkdir('artifacts', { recursive: true });
async function noOverflow() { assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true); }
async function formTest(kind, role) {
  const form = card(kind, 'In a form');
  await form.getByRole('button', { name: 'Save preferences' }).click();
  const first = form.getByRole(role).first();
  assert.equal(await first.evaluate(el => el === document.activeElement), true);
  assert.equal(await first.getAttribute('aria-invalid'), 'true');
  assert.match(await first.getAttribute('aria-describedby'), /error/);
  await first.check();
  assert.equal(await form.locator('.selection-error').count(), 0);
  await form.getByRole('button', { name: 'Save preferences' }).click();
  assert.equal(await form.locator('button[type=submit]').getAttribute('data-status'), 'success');
  assert.equal(await form.locator('form').evaluate(el => [...new FormData(el)].length), 1);
  await form.getByRole('button', { name: 'Reset' }).click();
  assert.equal(await first.isChecked(), false);
}
try {
  await openCatalog(page, `${base}/?component=builtin-radio-group`);
  await page.getByRole('heading', { name: 'Radio Group', exact: true }).waitFor();
  assert.equal(await page.locator('.gallery-card').count(), 15);
  const classic = card('Radio Group', 'Classic vertical');
  await classic.getByText('Push', { exact: true }).click();
  assert.equal(await classic.locator('input:checked').count(), 1);
  assert.equal(await classic.getByRole('radio', { name: 'Push', exact: true }).isChecked(), true);
  await classic.getByRole('radio', { name: 'Push', exact: true }).press('ArrowDown');
  const sms = classic.getByRole('radio', { name: 'SMS', exact: true });
  assert.equal(await sms.isChecked(), true);
  assert.equal(await sms.evaluate(el => getComputedStyle(el.nextElementSibling).borderTopStyle), 'solid');
  const info = card('Radio Group', 'Secondary information');
  await info.getByRole('radio', { name: 'Push' }).focus();
  await info.getByRole('radio', { name: 'Push' }).press('ArrowDown');
  assert.equal(await info.getByRole('radio', { name: 'Email' }).isChecked(), true);
  assert.equal(await info.getByRole('radio', { name: 'SMS' }).isDisabled(), true);
  const conditional = card('Radio Group', 'Conditional content');
  await conditional.getByRole('radio', { name: 'Daily digest' }).check();
  assert.equal(await conditional.getByLabel('Delivery time').isVisible(), true);
  await conditional.getByRole('radio', { name: 'As it happens' }).check();
  assert.equal(await conditional.getByLabel('Delivery time').count(), 0);
  await formTest('Radio Group', 'radio');
  await page.getByRole('button', { name: 'Column', exact: true }).click();
  assert.equal(await card('Radio Group', 'Pricing cards').locator('.radio-options--vertical').count(), 1);
  await page.getByRole('button', { name: 'Responsive grid', exact: true }).click();
  await card('Radio Group', 'Cards with images').getByRole('button', { name: /View code/ }).click();
  assert.match(await page.getByRole('dialog').locator('pre').innerText(), /export function RadioDemo/);
  await page.keyboard.press('Escape');
  const lab = page.locator('.selection-state-lab');
  await lab.getByRole('switch', { name: 'Default value' }).uncheck();
  assert.equal(await lab.locator('input[type=radio]:checked').count(), 0);
  await lab.getByRole('switch', { name: 'Default value' }).check();
  assert.equal(await lab.getByRole('radio', { name: 'Managed' }).isChecked(), true);
  await lab.getByRole('switch', { name: 'Disable group' }).check();
  assert.equal(await lab.locator('input[type=radio]:enabled').count(), 0);
  await lab.getByRole('switch', { name: 'Disable group' }).uncheck();
  await lab.getByRole('switch', { name: 'Dark surface' }).check();
  await lab.scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/radio-dark.png' });
  await page.getByRole('button', { name: 'Surfaces', exact: true }).click();
  await card('Radio Group', 'Cards with images').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/radio-desktop.png' });
  for (const width of [1024, 390]) { await page.setViewportSize({ width, height: 844 }); await noOverflow(); }
  await card('Radio Group', 'Pricing cards').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/radio-mobile.png' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.radio-disc').first().evaluate(el => getComputedStyle(el).transitionDuration), '0s');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await openCatalog(page, `${base}/?component=builtin-switch`);
  await page.getByRole('heading', { name: 'Switch', exact: true }).waitFor();
  assert.equal(await page.locator('.gallery-card').count(), 13);
  const labeled = card('Switch', 'Label on the right');
  await labeled.getByText('Automatic backup', { exact: true }).click();
  assert.equal(await labeled.getByRole('switch').isChecked(), true);
  await labeled.getByRole('switch').press('Space');
  assert.equal(await labeled.getByRole('switch').isChecked(), false);
  assert.equal(await labeled.getByRole('switch').evaluate(el => getComputedStyle(el.nextElementSibling).borderTopStyle), 'solid');
  const settings = card('Switch', 'Settings list');
  await settings.getByRole('switch', { name: 'Weekly summary' }).check();
  assert.equal(await settings.locator('input:checked').count(), 2);
  const content = card('Switch', 'Conditional content');
  await content.getByRole('switch', { name: 'Automatic backup' }).check();
  assert.equal(await content.getByLabel('Backup folder').isVisible(), true);
  await content.getByRole('switch', { name: 'Automatic backup' }).uncheck();
  assert.equal(await content.getByLabel('Backup folder').count(), 0);
  await formTest('Switch', 'switch');
  const asyncCard = card('Switch', 'Async save');
  const backup = asyncCard.getByRole('switch', { name: 'Cloud backup' });
  await backup.check();
  assert.equal(await backup.isDisabled(), true);
  assert.equal(await backup.getAttribute('aria-busy'), 'true');
  await asyncCard.getByText('Backup enabled.', { exact: true }).waitFor();
  assert.equal(await backup.isEnabled(), true);
  await asyncCard.getByRole('switch', { name: 'Simulate a failed save' }).check();
  await backup.uncheck();
  await asyncCard.locator('.selection-error').waitFor();
  assert.equal(await backup.isChecked(), true);
  await asyncCard.getByRole('switch', { name: 'Simulate a failed save' }).uncheck();
  await backup.uncheck();
  await asyncCard.getByText('Backup disabled.', { exact: true }).waitFor();
  assert.equal(await asyncCard.locator('.selection-error').count(), 0);
  await page.locator('.selection-state-lab').getByRole('switch', { name: 'Dark surface' }).check();
  await page.locator('.selection-state-lab').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/switch-dark.png' });
  await page.getByRole('button', { name: 'Essentials', exact: true }).click();
  await page.evaluate(() => scrollTo(0,0));
  await page.screenshot({ path: 'artifacts/switch-desktop.png' });
  for (const width of [1024, 390]) { await page.setViewportSize({ width, height: 844 }); await noOverflow(); }
  await card('Switch', 'With description').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/switch-mobile.png' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.switch-thumb').first().evaluate(el => getComputedStyle(el).transitionDuration), '0s');
  await page.getByRole('button', { name: 'All', exact: true }).click();
  await noOverflow();
  assert.deepEqual(errors, []);
  console.log('PASS: 28 compositions, radio exclusivity and arrows, switch labels and Space, disabled/default states, cards, forms, reset, conditional fields, async success/failure/retry, source dialog, mobile/tablet/desktop, dark and reduced motion.');
} finally { await browser.close(); }
