import React, { useState } from 'react';
import { Badge, StatusDot } from '../Badge/Badge';
import { Button } from '../Button/Button';
import { Tabs } from './Tabs';

function TabIcon({name}){const paths={overview:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,activity:<><path d="M4 12h3l2.2-5 4.1 11 2.2-6H20"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M4.9 4.9 7 7m10 10 2.1 2.1M19.1 4.9 17 7M7 17l-2.1 2.1"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function ProjectPanel({ section, title, children, footer }) {
  return <div className="tabs-project-panel"><span className="tabs-project-panel__eyebrow">Workspace / {section}</span><h4>{title}</h4><p>{children}</p><div className="tabs-project-panel__footer"><TabIcon name={section}/><span>{footer}</span></div></div>;
}
const panels={
  overview:<ProjectPanel section="overview" title="A shared perspective" footer="Project overview">A calm summary of the project’s current direction.</ProjectPanel>,
  activity:<ProjectPanel section="activity" title="The latest, together" footer="Team activity">Recent changes, comments, and completed reviews.</ProjectPanel>,
  settings:<ProjectPanel section="settings" title="Make room for your flow" footer="Workspace preferences">Visibility, notifications, and collaboration preferences.</ProjectPanel>
};
const baseItems=()=>[{value:'overview',label:'Overview',panel:panels.overview},{value:'activity',label:'Activity',panel:panels.activity},{value:'settings',label:'Settings',panel:panels.settings}];
export const tabsExamples=[['Contained','Appearance'],['Underline','Appearance'],['Centered','Appearance'],['End aligned','Appearance'],['Vertical','Appearance'],['Full width','Appearance'],['Icons and text','Content'],['Text and badge','Content'],['Counter','Content'],['Icon only','Content'],['Disabled tab','States'],['Long labels','States'],['Many tabs and overflow','States'],['Links pattern','Contexts'],['Unsaved indicator','Contexts'],['Manual activation','Keyboard'],['Keep mounted','Behavior'],['Loading panel','States'],['Empty panel','States'],['Error panel','States'],['Right to left','Direction']];
function simple(example){let items=baseItems();let props={items};if(example==='Underline')props.variant='underline';if(example==='Centered')props.alignment='center';if(example==='End aligned')props.alignment='end';if(example==='Vertical')props.orientation='vertical';if(example==='Full width')props.width='full';if(example==='Manual activation')props.activation='manual';if(example==='Keep mounted')props.keepMounted=true;if(example==='Right to left')props.dir='rtl';if(example==='Icons and text')items=items.map((item,i)=>({...item,icon:<TabIcon name={['overview','activity','settings'][i]}/>}));if(example==='Text and badge')items[1]={...items[1],meta:<Badge size="sm" tone="info">New</Badge>};if(example==='Counter')items[1]={...items[1],meta:<Badge size="sm" appearance="outline" shape="pill">8</Badge>};if(example==='Icon only')items=items.map((item,i)=>({...item,label:<span className="sr-only">{item.label}</span>,icon:<TabIcon name={['overview','activity','settings'][i]}/>}));if(example==='Disabled tab')items[1]={...items[1],disabled:true};if(example==='Long labels')items=[{...items[0],label:'Project overview and direction'},{...items[1],label:'Recent team activity'},{...items[2],label:'Workspace preferences'}];if(example==='Many tabs and overflow')items=['Overview','Activity','Files','Decisions','Milestones','People','Settings'].map((label,i)=>({value:String(i),label,panel:<p>{label} content remains reachable without shrinking every label.</p>}));if(example==='Links pattern')items=items.map(item=>({...item,href:`#tabs-${item.value}`,label:<>{item.label}<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></>}));if(example==='Unsaved indicator')items[2]={...items[2],meta:<Badge size="sm" tone="warning" shape="circle" aria-label="Unsaved changes"><StatusDot/></Badge>};if(example==='Loading panel')items[1]={...items[1],panel:<div className="tabs-state"><span className="tabs-loader"/><strong>Loading activity…</strong><small>Fetching the latest events.</small></div>};if(example==='Empty panel')items[1]={...items[1],panel:<div className="tabs-state"><strong>No activity yet</strong><small>Changes will appear here as the team works.</small><Button size="sm" variant="outline">Invite teammate</Button></div>};if(example==='Error panel')items[1]={...items[1],panel:<div className="tabs-state tabs-state--error"><strong>Activity could not be loaded</strong><small>Check your connection and try again.</small><Button size="sm" variant="destructive-outline">Try again</Button></div>};props.items=items;return props;}
export function TabsDemo({example='Contained'}){const props=simple(example);return <Tabs {...props} label={`${example} example`}/>}
export function ControlledTabs(){const[value,setValue]=useState('overview');return <div className="tabs-controlled"><Tabs items={baseItems()} value={value} onValueChange={setValue}/><span>Controlled value: <code>{value}</code></span></div>}
export function TabsSizeLab(){return <div className="tabs-size-lab">{['sm','md','lg'].map(size=><div key={size}><span>{size}</span><Tabs size={size} items={baseItems()} label={`${size} tabs`}/></div>)}</div>}
