import { Card } from '../Card/Card';
import React, { useState } from 'react';
import { CardsCarousel } from './CardsCarousel';
import { Button } from '../Button/Button';

export const storyItems = [
  { id:'perspective', takeaway:'Sketch three ways to approach the same question. Start with the least familiar.', category:'01 / Perspective', title:'Find a different point of view.', src:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85', alt:'A dramatic mountain ridge beneath a cloudy sky', content:<><h3>Step back. See what changes.</h3><p>A familiar problem can look very different from a little further away. Before opening another file, write down the question you are actually trying to answer.</p><p>Collect three approaches. Give each one a small sketch, a clear intention and enough room to surprise you. The first idea is a starting point.</p></> },
  { id:'focus', takeaway:'Choose one task. Give it twenty quiet minutes and your full attention.', category:'02 / Focus', title:'Make room for what matters.', src:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85', alt:'A lakeside cabin with mountains reflected in still water', content:<><h3>A little space goes a long way.</h3><p>Choose one thing to move forward today. Close the extra tabs, clear a corner of your desk and give that task a quiet stretch of attention.</p><p>Keep a separate place for everything that comes to mind. You can return to those thoughts when the work in front of you has had its turn.</p></> },
  { id:'explore', takeaway:'Save one unexpected reference. Write a sentence about what you noticed.', category:'03 / Discovery', title:'Follow your curiosity.', src:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1000&q=85', alt:'Sunlight reaching the floor of a dense green forest', content:<><h3>Leave the familiar path.</h3><p>Look for references outside your usual collection. A book cover, a walking route or the way light falls across a room can suggest a new rhythm for your work.</p><p>Save the observation alongside a sentence about why it caught your attention. That small note will be more useful than a folder full of unexplained images.</p></> },
  { id:'rhythm', takeaway:'Before you stop, leave yourself a note with the next small step.', category:'04 / Practice', title:'Find your own rhythm.', src:'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1000&q=85', alt:'Ocean waves rolling beneath a wide open sky', content:<><h3>Build a practice you can return to.</h3><p>Start with a small, repeatable session. Make something, look at it carefully and write down the next adjustment before you stop.</p><p>Progress becomes easier to see when you keep the early versions. Let the collection remind you how far a series of small decisions can take you.</p></> },
  { id:'essentials', takeaway:'Remove one element. See whether the rest becomes easier to understand.', category:'05 / Simplicity', title:'Keep the essential things.', src:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1000&q=85', alt:'Warm sandstone formations in a desert landscape', content:<><h3>Give every detail a reason.</h3><p>Read the work from the beginning. Notice where it asks for attention and whether that attention helps someone understand what to do next.</p><p>Remove one unnecessary element. Adjust the spacing around what remains. A clear hierarchy often comes from making fewer things compete.</p></> },
];

export const cardsExamples = [['Editorial collection', 'Composition'], ['Compact cards', 'Composition'], ['Dark surface', 'Composition'], ['Single story', 'Behavior']];
export function CardsCarouselDemo({ example }) {
  return <CardsCarousel items={example === 'Single story' ? storyItems.slice(0,1) : storyItems} label={example} title={example === 'Single story' ? 'One story worth your time.' : 'Good ideas start here.'} size={example === 'Compact cards' ? 'compact' : 'large'} theme={example === 'Dark surface' ? 'dark' : 'light'} />;
}
export function CardsCarouselPlayground() {
  const [size, setSize] = useState('large');
  const [theme, setTheme] = useState('light');
  return <Card variant="elevated" interactive className="cards-playground playground-card" aria-label="Cards Carousel playground"><CardsCarousel items={storyItems} label="Studio stories" title="A little more to discover." size={size} theme={theme} /><div className="cards-controls"><fieldset><legend>Card size</legend><div>{['large','compact'].map(value => <Button key={value} variant="outline" size="sm" selected={size === value} onClick={() => setSize(value)}>{value === 'large' ? 'Large' : 'Compact'}</Button>)}</div></fieldset><fieldset><legend>Surface</legend><div>{['light','dark'].map(value => <Button key={value} variant="outline" size="sm" selected={theme === value} onClick={() => setTheme(value)}>{value === 'light' ? 'Light' : 'Dark'}</Button>)}</div></fieldset></div></Card>;
}
export function CardsCarouselPreview() {
  return <span className="cards-mini">{storyItems.slice(0,2).map(item => <span key={item.id}><strong>{item.title}</strong><img src={item.src.replace('w=1000','w=300')} alt="" loading="lazy" /></span>)}</span>;
}
